// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9naXK0uiGnuP0q-insieSrbe3yV5jgU8',
    appId: '1:263754608153:web:7a6157c182eb04a66fc488',
    messagingSenderId: '263754608153',
    projectId: 'whatsapp-clone-75178',
    authDomain: 'whatsapp-clone-75178.firebaseapp.com',
    storageBucket: 'whatsapp-clone-75178.appspot.com',
    measurementId: 'G-BS7BNXYKPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSVgAvM_HQVcjQNIMhhT-7YgFhoCvt_yQ',
    appId: '1:263754608153:android:fc3028550122a1336fc488',
    messagingSenderId: '263754608153',
    projectId: 'whatsapp-clone-75178',
    storageBucket: 'whatsapp-clone-75178.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3wJzhiGQI1ncbTKob6VcxyjVgezALRZE',
    appId: '1:263754608153:ios:ddca87ae6961bd0f6fc488',
    messagingSenderId: '263754608153',
    projectId: 'whatsapp-clone-75178',
    storageBucket: 'whatsapp-clone-75178.appspot.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3wJzhiGQI1ncbTKob6VcxyjVgezALRZE',
    appId: '1:263754608153:ios:3b5d9c17a1cf8baa6fc488',
    messagingSenderId: '263754608153',
    projectId: 'whatsapp-clone-75178',
    storageBucket: 'whatsapp-clone-75178.appspot.com',
    iosBundleId: 'com.example.whatsappClone.RunnerTests',
  );
}
